name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Program Check
      run: |
        python main.py
      continue-on-error: false

    - name: Package Application
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cs2-noflash
        path: dist/main.exe
